/**
 * @file Version.h
 * @brief Version information for EE871.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef EE871_VERSION_STRING
#define EE871_VERSION_STRING "0.2.1"
#endif

#ifndef EE871_BUILD_DATE
#define EE871_BUILD_DATE __DATE__
#endif

#ifndef EE871_BUILD_TIME
#define EE871_BUILD_TIME __TIME__
#endif

#ifndef EE871_BUILD_TIMESTAMP
#define EE871_BUILD_TIMESTAMP EE871_BUILD_DATE " " EE871_BUILD_TIME
#endif

#ifndef EE871_GIT_COMMIT
#define EE871_GIT_COMMIT "unknown"
#endif

#ifndef EE871_GIT_STATUS
#define EE871_GIT_STATUS "unknown"
#endif

#ifndef EE871_VERSION_FULL
#define EE871_VERSION_FULL EE871_VERSION_STRING " (" EE871_GIT_COMMIT ", " EE871_BUILD_TIMESTAMP ", " EE871_GIT_STATUS ")"
#endif

namespace EE871 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 0;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 2;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 1;

/// @brief Full semantic version string.
static constexpr const char* VERSION = EE871_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 201;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 201;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = EE871_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = EE871_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = EE871_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = EE871_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = EE871_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = EE871_VERSION_FULL;

}  // namespace EE871
